apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80 # Port sur lequel le service sera accessible à l'extérieur
      targetPort: 8888 # Port correspondant au containerPort du déploiement
  type: LoadBalancer # Ou un autre type selon votre besoin et environnement
